import pandas as pd
from pprint import pprint

# Days of reports to collect
days = [
    "03-10-2020",
    "03-11-2020",
    "03-12-2020",
    "03-13-2020",
    "03-14-2020",
    "03-15-2020",
    "03-16-2020",
    "03-17-2020",
    "03-18-2020",
    "03-19-2020",
    "03-20-2020",
    "03-21-2020",
    "03-22-2020",
    "03-23-2020",
    "03-24-2020",
    "03-25-2020",
    "03-26-2020",
    "03-27-2020",
    "03-28-2020",
    "03-29-2020",
    "03-30-2020",
    "03-31-2020",
    "04-01-2020",
    "04-02-2020",
    "04-03-2020",
    "04-04-2020",
    "04-05-2020",
    "04-06-2020",
    "04-07-2020",
    "04-08-2020",
    "04-09-2020",
    "04-10-2020",
]

data_url_template = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/" \
                    "csse_covid_19_data/" \
                    "csse_covid_19_daily_reports/"
# This dictionary is used to consolidate the data
# where the labels aren't consistent
names_dict = {
    'Mainland China': 'China',
    'China': 'China',
    'Macau': 'China',
    'South Korea': 'South Korea',
    'Korea, South': 'South Korea',
    'Republic of Korea': 'South Korea',
    'Italy': 'Italy',
    'Yemen': 'Yemen',
    'Iran': 'Iran',
    'Iran (Islamic Republic of)': 'Iran',
    'France': 'France',
    'Germany': 'Germany',
    'Spain': 'Spain',
    'Japan': 'Japan',
    'Switzerland': 'Switzerland',
    'UK': 'United Kingdom',
    'United Kingdom': 'United Kingdom',
    'Netherlands': 'Netherlands',
    'Belgium': 'Belgium',
    'Sweden': 'Sweden',
    'Norway': 'Norway',
    'Singapore': 'Singapore',
    'Hong Kong': 'Hong Kong',
    'Hong Kong SAR': 'Hong Kong',
    'Malaysia': 'Malaysia',
    'Bahrain': 'Bahrain',
    'Austria': 'Austria',
    'US': 'US',
    'Kuwait': 'Kuwait',
    'Iraq': 'Iraq',
    'Iceland': 'Iceland',
    'Thailand': 'Thailand',
    'Greece': 'Greece',
    'Taiwan': 'Taiwan',
    'Taiwan*': 'Taiwan',
    'Taipei and environs': 'Taiwan',
    'United Arab Emirates': 'United Arab Emirates',
    'India': 'India',
    'Australia': 'Australia',
    'Canada': 'Canada',
    'Denmark': 'Denmark',
    'San Marino': 'San Marino',
    'Lebanon': 'Lebanon',
    'Palestine': 'Palestine',
    'occupied Palestinian territory': 'Palestine',
    'West Bank and Gaza': 'Palestine',
    'Israel': 'Israel',
    'Portugal': 'Portugal',
    'Czech Republic': 'Czech Republic',
    'Ireland': 'Ireland',
    'Republic of Ireland': 'Ireland',
    'Vietnam': 'Vietnam',
    'Viet Nam': 'Vietnam',
    'Algeria': 'Algeria',
    'Oman': 'Oman',
    'Egypt': 'Egypt',
    'Finland': 'Finland',
    'Brazil': 'Brazil',
    'Ecuador': 'Ecuador',
    'Russia': 'Russia',
    'Russian Federation': 'Russia',
    'Croatia': 'Croatia',
    'Estonia': 'Estonia',
    'Azerbaijan': 'Azerbaijan',
    'Romania': 'Romania',
    'Argentina': 'Argentina',
    'Qatar': 'Qatar',
    'Slovenia': 'Slovenia',
    'Belarus': 'Belarus',
    'Mexico': 'Mexico',
    'Pakistan': 'Pakistan',
    'Philippines': 'Philippines',
    'French Guiana': 'French Guiana',
    'New Zealand': 'New Zealand',
    'Poland': 'Poland',
    'Saudi Arabia': 'Saudi Arabia',
    'Chile': 'Chile',
    'Georgia': 'Georgia',
    'Hungary': 'Hungary',
    'Indonesia': 'Indonesia',
    'Senegal': 'Senegal',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Malta': 'Malta',
    'North Macedonia': 'Macedonia',
    'Saint Barthelemy': 'Saint Barthelemy',
    'Dominican Republic': 'Dominican Republic',
    'Luxembourg': 'Luxembourg',
    'Martinique': 'Martinique',
    'Morocco': 'Morocco',
    'Afghanistan': 'Afghanistan',
    'Andorra': 'Andorra',
    'Armenia': 'Armenia',
    'Bhutan': 'Bhutan',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Colombia': 'Colombia',
    'Costa Rica': 'Costa Rica',
    'Faroe Islands': 'Faroe Islands',
    'Gibraltar': 'Gibraltar',
    'Jordan': 'Jordan',
    'Latvia': 'Latvia',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lithuania',
    'Monaco': 'Monaco',
    'Nepal': 'Nepal',
    'Nigeria': 'Nigeria',
    'Peru': 'Peru',
    'Serbia': 'Serbia',
    'Slovakia': 'Slovakia',
    'South Africa': 'South Africa',
    'Sri Lanka': 'Sri Lanka',
    'Togo': 'Togo',
    'Tunisia': 'Tunisia',
    'Ukraine': 'Ukraine',
    'Vatican City': 'Vatican City',
    'Holy See': 'Vatican City',
    'Bulgaria': 'Bulgaria',
    'Maldives': 'Maldives',
    'Macao SAR': 'Macao',
    'Moldova': 'Moldova',
    'Republic of Moldova': 'Moldova',
    'St. Martin': 'Saint Martin',
    'Saint Martin': 'Saint Martin',
    'Bangladesh': 'Bangladesh',
    'Paraguay': 'Paraguay',
    'Albania': 'Albania',
    'Cyprus': 'Cyprus',
    'Brunei': 'Brunei',
    'Burkina Faso': 'Burkina Faso',
    'Mongolia': 'Mongolia',
    'Panama': 'Panama',
    'Czechia': 'Czech Republic',
    'Bolivia': 'Bolivia',
    'Honduras': 'Honduras',
    'Congo (Kinshasa)': 'Congo',
    'Republic of the Congo': 'Congo',
    'Congo (Brazzaville)': 'Congo',
    "Cote d'Ivoire": "Cote d'Ivoire",
    'Jamaica': 'Jamaica',
    'Reunion': 'Reunion',
    'Turkey': 'Turkey',
    'Cuba': 'Cuba',
    'Guyana': 'Guyana',
    'Kazakhstan': 'Kazakhstan',
    'Cayman Islands': 'Cayman Islands',
    'Guadeloupe': 'Guadeloupe',
    'Ethiopia': 'Ethiopia',
    'Sudan': 'Sudan',
    'Guinea': 'Guinea',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    'Aruba': 'Aruba',
    'Kenya': 'Kenya',
    'Uruguay': 'Uruguay',
    'Ghana': 'Ghana',
    'Jersey': 'Channel Islands',
    'Channel Islands': 'Channel Islands',
    'Guernsey': 'Channel Islands',
    'Namibia': 'Namibia',
    'Seychelles': 'Seychelles',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Venezuela': 'Venezuela',
    'Curacao': 'Curacao',
    'Eswatini': 'Eswatini',
    'Gabon': 'Gabon',
    'Guatemala': 'Guatemala',
    'Mauritania': 'Mauritania',
    'Rwanda': 'Rwanda',
    'Saint Lucia': 'Saint Lucia',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Suriname': 'Suriname',
    'Kosovo': 'Kosovo',
    'Central African Republic': 'Central African Republic',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Uzbekistan': 'Uzbekistan',
    'Guam': 'Guam',
    'Puerto Rico': 'Puerto Rico',
    'Benin': 'Benin',
    'Greenland': 'Greenland',
    'Liberia': 'Liberia',
    'Mayotte': 'Mayotte',
    'Somalia': 'Somalia',
    'Tanzania': 'Tanzania',
    'The Bahamas': 'Bahamas',
    'Bahamas, The': 'Bahamas',
    'Bahamas': 'Bahamas',
    'The Gambia': 'Gambia',
    'Gambia, The': 'Gambia',
    'Gambia': 'Gambia',
    'Western Sahara': 'Western Sahara',
    'Barbados': 'Barbados',
    'Montenegro': 'Montenegro',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Mauritius': 'Mauritius',
    'Zambia': 'Zambia',
    'Djibouti': 'Djibouti',
    'Chad': 'Chad',
    'El Salvador': 'El Salvador',
    'Fiji': 'Fiji',
    'Nicaragua': 'Nicaragua',
    'Madagascar': 'Madagascar',
    'Haiti': 'Haiti',
    'Angola': 'Angola',
    'Cabo Verde': 'Cape Verde',
    'Cape Verde': 'Cape Verde',
    'Niger': 'Niger',
    'Papua New Guinea': 'Papua New Guinea',
    'Zimbabwe': 'Zimbabwe',
    'East Timor': 'Timor-Leste',
    'Timor-Leste': 'Timor-Leste',
    'Eritrea': 'Eritrea',
    'Uganda': 'Uganda',
    'Dominica': 'Dominica',
    'Grenada': 'Grenada',
    'Mozambique': 'Mozambique',
    'Syria': 'Syria',
    'Belize': 'Belize',
    'Laos': 'Laos',
    'Libya': 'Libya',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Mali': 'Mali',
    'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
    'Burma': 'Burma',
    'Botswana': 'Botswana',
    'Burundi': 'Burundi',
    'Sierra Leone': 'Sierra Leone',
    'Malawi': 'Malawi',
    'South Sudan': 'South Sudan',
    'Sao Tome and Principe': 'Sao Tome and Principe'
}

countries_lat_lon = {
    'China': {'lat': 35.0, 'lon': 105.0},
    'South Korea': {'lat': 37.0, 'lon': 127.5},
    'Italy': {'lat': 42.83, 'lon': 12.83},
    'Iran': {'lat': 32.0, 'lon': 53.0},
    'France': {'lat': 46.0, 'lon': 2.0},
    'Germany': {'lat': 51.0, 'lon': 9.0},
    'Spain': {'lat': 40.0, 'lon': -4.0},
    'Japan': {'lat': 36.0, 'lon': 138.0},
    'Switzerland': {'lat': 47.0, 'lon': 8.0},
    'United Kingdom': {'lat': 54.0, 'lon': -2.0},
    'Netherlands': {'lat': 52.5, 'lon': 5.75},
    'Belgium': {'lat': 50.83, 'lon': 4.0},
    'Sweden': {'lat': 62.0, 'lon': 15.0},
    'Norway': {'lat': 62.0, 'lon': 10.0},
    'Singapore': {'lat': 1.37, 'lon': 103.8},
    'Hong Kong': {'lat': 22.25, 'lon': 114.17},
    'Malaysia': {'lat': 2.5, 'lon': 112.5},
    'Bahrain': {'lat': 26.0, 'lon': 50.55},
    'Austria': {'lat': 47.33, 'lon': 13.33},
    'US': {'lat': 38.0, 'lon': -97.0},
    'Kuwait': {'lat': 29.34, 'lon': 47.66},
    'Iraq': {'lat': 33.0, 'lon': 44.0},
    'Iceland': {'lat': 65.0, 'lon': -18.0},
    'Thailand': {'lat': 15.0, 'lon': 100.0},
    'Greece': {'lat': 39.0, 'lon': 22.0},
    'Taiwan': {'lat': 23.5, 'lon': 121.0},
    'United Arab Emirates': {'lat': 24.0, 'lon': 54.0},
    'India': {'lat': 20.0, 'lon': 77.0},
    'Australia': {'lat': -27.0, 'lon': 133.0},
    'Canada': {'lat': 60.0, 'lon': -95.0},
    'Denmark': {'lat': 56.0, 'lon': 10.0},
    'San Marino': {'lat': 43.77, 'lon': 12.42},
    'Lebanon': {'lat': 33.83, 'lon': 35.83},
    'Palestine': {'lat': 32.0, 'lon': 35.25},
    'Israel': {'lat': 31.5, 'lon': 34.75},
    'Portugal': {'lat': 39.5, 'lon': -8.0},
    'Czech Republic': {'lat': 49.75, 'lon': 15.5},
    'Ireland': {'lat': 53.0, 'lon': -8.0},
    'Vietnam': {'lat': 16.0, 'lon': 106.0},
    'Algeria': {'lat': 28.0, 'lon': 3.0},
    'Oman': {'lat': 21.0, 'lon': 57.0},
    'Egypt': {'lat': 27.0, 'lon': 30.0},
    'Channel Islands': {'lat': 49.20, 'lon': -2.13},
    'Finland': {'lat': 64.0, 'lon': 26.0},
    'Brazil': {'lat': -10.0, 'lon': -55.0},
    'Ecuador': {'lat': -2.0, 'lon': -77.5},
    'Russia': {'lat': 60.0, 'lon': 100.0},
    'Croatia': {'lat': 45.17, 'lon': 15.5},
    'Estonia': {'lat': 59.0, 'lon': 26.0},
    'Azerbaijan': {'lat': 40.5, 'lon': 47.5},
    'Romania': {'lat': 46.0, 'lon': 25.0},
    'Argentina': {'lat': -34.0, 'lon': -64.0},
    'Qatar': {'lat': 25.5, 'lon': 51.25},
    'Slovenia': {'lat': 46.0, 'lon': 15.0},
    'Belarus': {'lat': 53.0, 'lon': 28.0},
    'Mexico': {'lat': 23.0, 'lon': -102.0},
    'Pakistan': {'lat': 30.0, 'lon': 70.0},
    'Philippines': {'lat': 13.0, 'lon': 122.0},
    'French Guiana': {'lat': 4.0, 'lon': -53.0},
    'New Zealand': {'lat': -41.0, 'lon': 174.0},
    'Poland': {'lat': 52.0, 'lon': 20.0},
    'Saudi Arabia': {'lat': 25.0, 'lon': 45.0},
    'Chile': {'lat': -30.0, 'lon': -71.0},
    'Georgia': {'lat': 42.0, 'lon': 43.5},
    'Hungary': {'lat': 47.0, 'lon': 20.0},
    'Indonesia': {'lat': -5.0, 'lon': 120.0},
    'Senegal': {'lat': 14.0, 'lon': -14.0},
    'Bosnia and Herzegovina': {'lat': 44.0, 'lon': 18.0},
    'Malta': {'lat': 35.83, 'lon': 14.58},
    'Macedonia': {'lat': 41.83, 'lon': 22.0},
    'Saint Barthelemy': {'lat': 17.90, 'lon': -62.83},
    'Dominican Republic': {'lat': 19.0, 'lon': -70.67},
    'Luxembourg': {'lat': 49.75, 'lon': 6.17},
    'Martinique': {'lat': 14.67, 'lon': -61.0},
    'Morocco': {'lat': 32.0, 'lon': -5.0},
    'Afghanistan': {'lat': 33.0, 'lon': 65.0},
    'Andorra': {'lat': 42.5, 'lon': 1.5},
    'Armenia': {'lat': 40.0, 'lon': 45.0},
    'Bhutan': {'lat': 27.5, 'lon': 90.5},
    'Cambodia': {'lat': 13.0, 'lon': 105.0},
    'Cameroon': {'lat': 6.0, 'lon': 12.0},
    'Colombia': {'lat': 4.0, 'lon': -72.0},
    'Costa Rica': {'lat': 10.0, 'lon': -84.0},
    'Faroe Islands': {'lat': 62.0, 'lon': -7.0},
    'Gibraltar': {'lat': 36.18, 'lon': -5.37},
    'Jordan': {'lat': 31.0, 'lon': 36.0},
    'Latvia': {'lat': 57.0, 'lon': 25.0},
    'Liechtenstein': {'lat': 47.17, 'lon': 9.53},
    'Lithuania': {'lat': 56.0, 'lon': 24.0},
    'Monaco': {'lat': 43.73, 'lon': 7.4},
    'Nepal': {'lat': 28.0, 'lon': 84.0},
    'Nigeria': {'lat': 10.0, 'lon': 8.0},
    'Peru': {'lat': -10.0, 'lon': -76.0},
    'Serbia': {'lat': 44.0, 'lon': 21.0},
    'Slovakia': {'lat': 48.67, 'lon': 19.5},
    'South Africa': {'lat': -29.0, 'lon': 24.0},
    'Sri Lanka': {'lat': 7.0, 'lon': 81.0},
    'Togo': {'lat': 8.0, 'lon': 1.17},
    'Tunisia': {'lat': 34.0, 'lon': 9.0},
    'Ukraine': {'lat': 49.0, 'lon': 32.0},
    'Vatican City': {'lat': 41.9, 'lon': 12.45},
    'Bulgaria': {'lat': 43.0, 'lon': 25.0},
    'Maldives': {'lat': 3.25, 'lon': 73.0},
    'Macao': {'lat': 22.17, 'lon': 113.55},
    'Moldova': {'lat': 47.0, 'lon': 29.0},
    'Saint Martin': {'lat': 18.07, 'lon': -63.08},
    'Bangladesh': {'lat': 24.0, 'lon': 90.0},
    'Paraguay': {'lat': -23.0, 'lon': -58.0},
    'Albania': {'lat': 41.0, 'lon': 20.0},
    'Cyprus': {'lat': 35.0, 'lon': 33.0},
    'Brunei': {'lat': 4.5, 'lon': 114.67},
    'Burkina Faso': {'lat': 13.0, 'lon': -2.0},
    'Mongolia': {'lat': 46.0, 'lon': 105.0},
    'Panama': {'lat': 9.0, 'lon': -80.0},
    'Bolivia': {'lat': -17.0, 'lon': -65.0},
    'Honduras': {'lat': 15.0, 'lon': -86.5},
    'Congo': {'lat': 0.0, 'lon': 25.0},
    "Cote d'Ivoire": {'lat': 8.0, 'lon': -5.0},
    'Jamaica': {'lat': 18.25, 'lon': -77.5},
    'Reunion': {'lat': -21.1, 'lon': 55.6},
    'Turkey': {'lat': 39.0, 'lon': 35.0},
    'Cuba': {'lat': 21.5, 'lon': -80.0},
    'Guyana': {'lat': 5.0, 'lon': -59.0},
    'Kazakhstan': {'lat': 48.0, 'lon': 68.0},
    'Cayman Islands': {'lat': 19.5, 'lon': -80.5},
    'Guadeloupe': {'lat': 16.25, 'lon': -61.58},
    'Ethiopia': {'lat': 8.0, 'lon': 38.0},
    'Sudan': {'lat': 15.0, 'lon': 30.0},
    'Guinea': {'lat': 11.0, 'lon': -10.0},
    'Antigua and Barbuda': {'lat': 17.05, 'lon': -61.8},
    'Aruba': {'lat': 12.5, 'lon': -69.97},
    'Kenya': {'lat': 1.0, 'lon': 38.0},
    'Uruguay': {'lat': -33.0, 'lon': -56.0},
    'Ghana': {'lat': 8.0, 'lon': -2.0},
    'Namibia': {'lat': -22.0, 'lon': 17.0},
    'Seychelles': {'lat': -4.58, 'lon': 55.67},
    'Trinidad and Tobago': {'lat': 11.0, 'lon': -61.0},
    'Venezuela': {'lat': 8.0, 'lon': -66.0},
    'Curacao': {'lat': 12.17, 'lon': -68.99},
    'Eswatini': {'lat': -26.51, 'lon': 31.46},
    'Gabon': {'lat': -1.0, 'lon': 11.75},
    'Guatemala': {'lat': 15.5, 'lon': -90.25},
    'Mauritania': {'lat': 20.0, 'lon': -12.0},
    'Rwanda': {'lat': -2.0, 'lon': 30.0},
    'Saint Lucia': {'lat': 13.88, 'lon': -61.13},
    'Saint Vincent and the Grenadines': {'lat': 13.25, 'lon': -61.2},
    'Suriname': {'lat': 4.0, 'lon': -56.0},
    'Kosovo': {'lat': 42.66, 'lon': 21.16},
    'Central African Republic': {'lat': 7.0, 'lon': 21.0},
    'Equatorial Guinea': {'lat': 2.0, 'lon': 10.0},
    'Uzbekistan': {'lat': 41.0, 'lon': 64.0},
    'Guam': {'lat': 13.47, 'lon': 144.78},
    'Puerto Rico': {'lat': 18.25, 'lon': -66.5},
    'Benin': {'lat': 9.5, 'lon': 2.25},
    'Greenland': {'lat': 72.0, 'lon': -40.0},
    'Liberia': {'lat': 6.5, 'lon': -9.5},
    'Mayotte': {'lat': -12.83, 'lon': 45.17},
    'Somalia': {'lat': 10.0, 'lon': 49.0},
    'Tanzania': {'lat': -6.0, 'lon': 35.0},
    'Bahamas': {'lat': 24.25, 'lon': -76.0},
    'Gambia': {'lat': 13.47, 'lon': -16.57},
    'Western Sahara': {'lat': 24.5, 'lon': -13.0},
    'Barbados': {'lat': 13.17, 'lon': -59.53},
    'Montenegro': {'lat': 42.0, 'lon': 19.0},
    'Kyrgyzstan': {'lat': 41.0, 'lon': 75.0},
    'Mauritius': {'lat': -20.28, 'lon': 57.55},
    'Zambia': {'lat': -15.0, 'lon': 30.0},
    'Djibouti': {'lat': 11.5, 'lon': 43.0},
    'Chad': {'lat': 15.0, 'lon': 19.0},
    'El Salvador': {'lat': 13.83, 'lon': -88.92},
    'Fiji': {'lat': -18.0, 'lon': 175.0},
    'Nicaragua': {'lat': 13.0, 'lon': -85.0},
    'Madagascar': {'lat': -20.0, 'lon': 47.0},
    'Haiti': {'lat': 19.0, 'lon': -72.42},
    'Angola': {'lat': -12.5, 'lon': 18.5},
    'Cape Verde': {'lat': 16.0, 'lon': -24.0},
    'Niger': {'lat': 16.0, 'lon': 8.0},
    'Papua New Guinea': {'lat': -6.0, 'lon': 147.0},
    'Zimbabwe': {'lat': -20.0, 'lon': 30.0},
    'Timor-Leste': {'lat': -8.55, 'lon': 125.56},
    'Eritrea': {'lat': 15.0, 'lon': 39.0},
    'Uganda': {'lat': 1.0, 'lon': 32.0},
    'Dominica': {'lat': 15.42, 'lon': -61.33},
    'Grenada': {'lat': 12.12, 'lon': -61.67},
    'Mozambique': {'lat': -18.25, 'lon': 35.0},
    'Syria': {'lat': 35.0, 'lon': 38.0},
    'Belize': {'lat': 17.25, 'lon': -88.75},
    'Laos': {'lat': 18.0, 'lon': 105.0},
    'Libya': {'lat': 25.0, 'lon': 17.0},
    'Guinea-Bissau': {'lat': 12.0, 'lon': -15.0},
    'Mali': {'lat': 17.0, 'lon': -4.0},
    'Saint Kitts and Nevis': {'lat': 17.33, 'lon': -62.75},
    'Burma': {'lat': 16.87, 'lon': 96.19},
    'Botswana': {'lat': -22.0, 'lon': 24.0},
    'Burundi': {'lat': -3.5, 'lon': 30.0},
    'Sierra Leone': {'lat': 8.5, 'lon': -11.5},
    'Malawi': {'lat': -13.5, 'lon': 34.0},
    'South Sudan': {'lat': 4.85, 'lon': 31.57},
    'Sao Tome and Principe': {'lat': 0.25, 'lon': 6.60},
    'Yemen': {'lat': 15.0, 'lon': 48.0}
}

# initialize the list to hold the name of countries
names = []

# Loop through the days
for count, day in enumerate(days):
    # Get this day's data
    data = pd.read_csv(data_url_template + day + ".csv", error_bad_lines=False)

    print("Day:", day.split(".")[0])

    # Loop through the rows
    for index, item in data.iterrows():
        # Check if there is no data in this row
        if data["Confirmed"][index] == 0 and data["Deaths"][index] == 0 and data["Recovered"][index] == 0:
            continue

        # Check what the labeling style is
        if "Country/Region" in data.columns:
            if data["Country/Region"][index] in names:
                continue
            else:
                names.append(data["Country/Region"][index])
        else:
            if data["Country_Region"][index] in names:
                continue
            else:
                names.append(data["Country_Region"][index])

pprint(list(set(names) - set(names_dict.keys())))
pprint(list(set(names_dict.values()) - set(countries_lat_lon.keys())))
